spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shop_test?useSSL=false
        username: admin
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    flyway:
        locations: classpath:/db/migration,classpath:/db/migration_mock
    security:
        oauth2:
            clientId: my-trusted-client
            authorizedGrantTypes: password,authorization_code,refresh_token,implicit
            authorities: ROLE_CLIENT,ROLE_TRUSTED_CLIENT
            scopes: read,write,trust
            clientSecret: secret
            accessTokenValiditySeconds: 600
            refreshTokenValiditySeconds: 1200


server:
    port: 8090


online-shop:
    strategy: path
    api-key: AIzaSyBe3j5MuBUfrjp534Kv2-yrLGlJlgPSoSY
    proxy.name: proxy.msg.de
    proxy.port: 3128
    proxy.status: true
