spring:
        datasource:
            url: jdbc:mysql://localhost:3306/shop?useSSL=false
            username: admin
            password: admin
            driver-class-name: com.mysql.jdbc.Driver
        jpa.hibernate.ddl-auto: validate
server:
    port: 80

online-shop:
    strategy: single